--DROP TABLE IF EXISTS PUBLIC.TEXT_LINE;
--DROP INDEX IF EXISTS PUBLIC.IDX_TEXT_LINE_UCT;
CREATE TABLE IF NOT EXISTS PUBLIC.TEXT_LINE (UPPER_CASE_TEXT VARCHAR(2048) NOT NULL, TEXT_LINE VARCHAR(2048) NOT NULL, primary key (UPPER_CASE_TEXT));
